'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Citas
    Public Property id_cita As Integer
    Public Property fecha_cita As Date
    Public Property lugar As String
    Public Property id_paciente As Integer
    Public Property id_medico As Integer
    Public Property estado_cita As String
    Public Property receta_generada As Nullable(Of Boolean)

    Public Overridable Property Personas As Personas
    Public Overridable Property Personas1 As Personas

End Class
