'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB_GestionCitasEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB_GestionCitasEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Citas() As DbSet(Of Citas)
    Public Overridable Property Personas() As DbSet(Of Personas)
    Public Overridable Property Recetas() As DbSet(Of Recetas)

End Class
