'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Personas
    Public Property id As Integer
    Public Property nombre As String
    Public Property telefono As String
    Public Property tipo_persona As String
    Public Property correo As String

    Public Overridable Property Citas As ICollection(Of Citas) = New HashSet(Of Citas)
    Public Overridable Property Citas1 As ICollection(Of Citas) = New HashSet(Of Citas)
    Public Overridable Property Recetas As ICollection(Of Recetas) = New HashSet(Of Recetas)

End Class
