'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Recetas
    Public Property id_receta As Integer
    Public Property codigo_receta As String
    Public Property id_paciente As Integer
    Public Property medicamentos As String
    Public Property estado_receta As String
    Public Property fecha_creacion As Nullable(Of Date)
    Public Property fecha_vencimiento As Nullable(Of Date)

    Public Overridable Property Personas As Personas

End Class
